export const Cars = [
    {id: 1, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-1.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 2, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-2.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 3, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-3.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 4, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-4.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 5, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-5.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 6, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-6.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 7, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-1.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 8, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-2.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 9, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-6.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 10, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-3.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 11, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-4.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 12, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-5.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 13, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-6.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 14, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-1.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 15, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-2.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 16, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-3.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 17, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-4.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
    {id: 18, model: 'Toyota Corolla GQ', description: '2.5 Lt VHC Engine, 5dr Step Auto', image: '/sell/car-5.png', color: 'Blue', year: 2011, transmission: 'Automatic', type: 'Salon', price: 4700000 },
];