import React from "react";
import Head from "next/head";
import style from "../../styles/custom.module.css"
import Footer from "../components/Footer";

function LandingLayout({children, navbar=null, title='Welcome'}) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <meta name="description" content="Generated by create next app" />
                <link href="https://fonts.cdnfonts.com/css/poppins" rel="stylesheet" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.hero}>
                {navbar}
            </div>
            <main>
                { children }
            </main>
            <Footer/>
        </>
    )
}

export default LandingLayout
