import React from "react";
import Head from "next/head";
import LandingAppBar from "../components/NavBar";
import style from "../../styles/custom.module.css"
import Footer from "../components/Footer";

function LandingLayout({title='Welcome', children}) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={style.hero}>
                <LandingAppBar/>
            </div>
            <main>
                { children }
            </main>
            <Footer/>
        </>
    )
}

export default LandingLayout
